name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Create frontend directory and copy files
      run: |
        mkdir -p frontend
        cp templates/volunteer_points_platform.html frontend/index.html
        # 确保README.md不会被渲染为首页
        touch frontend/.nojekyll
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './frontend'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
